#PD Ping script, sloužící k ověřování dostupnosti serverů, které dle PD nejsou scanovány Tenable
#Radek Neumann; OIKB; radek.neumann@vzp.cz; 2020

#Vytvoření "unikátního názvu pro soubor se záznamem"
$fileName = Get-Date -Format "MM-dd-yyyy"
$fileName = $fileName + '.txt';

#Vytvoření záhlaví záznamu
$dateOfRun = Get-Date
$runas = whoami
$nameOfScripr = "PD-Ping 1.0" > C:\Users\neumr992\script_results\PD_pingable\$fileName 
$dateOfSet = "Checked: " + $dateOfRun >> C:\Users\neumr992\script_results\PD_pingable\$fileName
$runner = "User: " + $runas >> C:\Users\neumr992\script_results\PD_pingable\$fileName

$ServerName = Get-Content "C:\Users\neumr992\script_results\PD_pingable\IPAddresses.txt"  
  
foreach ($Server in $ServerName) {  
  
        if (test-Connection -ComputerName $Server -Count 2 -Quiet ) {   
          
            "$Server is Pinging "  >> C:\Users\neumr992\script_results\PD_pingable\$fileName
            "$Server is Pinging"
          
                    } else  
                      
                    {"$Server not pinging"  >> C:\Users\neumr992\script_results\PD_pingable\$fileName
                        "$Server not pinging"
              
                    }      
          
} 
Write-Host "Script PD PING ukončen!"
# SIG # Begin signature block
# MIIR8gYJKoZIhvcNAQcCoIIR4zCCEd8CAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUl7ErymquSpVUgqQwzN9uMpL0
# 0OGggg9DMIIEwDCCA6igAwIBAgITSQABwVkiuFRxW2TOLAAAAAHBWTANBgkqhkiG
# 9w0BAQsFADBhMQswCQYDVQQGEwJDWjE3MDUGA1UEChMuVnNlb2JlY25hIHpkcmF2
# b3RuaSBwb2ppc3Rvdm5hIENlc2tlIHJlcHVibGlreTEZMBcGA1UEAxMQVlpQLUlu
# dHJhbmV0LUNBMjAeFw0yMDA3MjEwODI5NThaFw0yNDA3MjAwODI5NThaMBMxETAP
# BgNVBAMTCG5ldW1yOTkyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
# mmwkJkiTg76kqwkPwTMt0z3/D8Kr7n1rDWOKyb5cddD1VLJTx6DMn1u3LOUojipe
# U+MQ+2+lM5eULF/npv9gkciJRQhxF1QpojIQncRj4NFhefZc9M8L0CCbJ66fFffl
# pljEBTcajSBryAFatZtSystbMmRFeZvSQQyhaxsAEqeMDFw4FoRHOVvtYk+nNRep
# jm2ZYs1X4ajSEkMv6SjAPVjKVskkpO23h9hUUC6BitC4i/BEzFshuCX5LeIJzDsN
# Nq46NAMP84foGuMYR0dymqLHCm9iZ0iGN+bptg5+K4Ya8j9E6+kOVGj83cNpuede
# 8j0UyR0a7Xz+jwZvKmjD4QIDAQABo4IBvTCCAbkwCwYDVR0PBAQDAgeAMDwGCSsG
# AQQBgjcVBwQvMC0GJSsGAQQBgjcVCIbbjieDmJxBkZM02/IPgq2mD4EUhIeOOYbv
# jCICAWQCAQ8wHQYDVR0OBBYEFA1/+bYDTWlxF8VH1VdNX8zbagaJMB8GA1UdIwQY
# MBaAFFNGECEkduJIS2IUyog3GBUq6SFqMHAGA1UdHwRpMGcwZaBjoGGGLmh0dHA6
# Ly9jYS52enAuY3ovY2VydGRhdGEvVlpQLUludHJhbmV0LUNBMi5jcmyGL2h0dHA6
# Ly9wa2kudnpwLmN6L2NlcnRkYXRhL1ZaUC1JbnRyYW5ldC1DQTIuY3JsMIGHBggr
# BgEFBQcBAQR7MHkwOgYIKwYBBQUHMAKGLmh0dHA6Ly9jYS52enAuY3ovY2VydGRh
# dGEvVlpQLUludHJhbmV0LUNBMi5jcnQwOwYIKwYBBQUHMAKGL2h0dHA6Ly9wa2ku
# dnpwLmN6L2NlcnRkYXRhL1ZaUC1JbnRyYW5ldC1DQTIuY3J0MBMGA1UdJQQMMAoG
# CCsGAQUFBwMDMBsGCSsGAQQBgjcVCgQOMAwwCgYIKwYBBQUHAwMwDQYJKoZIhvcN
# AQELBQADggEBAKqnitwRGfDgH3xosXOklBf1geIjqJLcTj32z78nx3roCYvvDYG+
# LpqRl0h9fkAjlKDbfL3Ftfa7o7qkxpjyZgljL6dhU/IQeiyw31JU+y/mhLDfo28i
# 7bVgXJLT9CCc9LjgjkidgPbxJsKvpVdIHTX81xLT+O8dxoBpnqe7Dl1AQfV1rmay
# NMKFNU5B2dbzrq8+JtNF43Y7kBpY5K+7qcECEIKbnAvU9qXVIhMuyNu28Kfv50fN
# q18/to/b+j93cMHlDLcwyfe3PkjaXdJu3G233a1KJTuDtgfuZu9nEcUy9oiwlwlD
# VaefJI8c1Ld422OTibgaD+JsL24cnvFuPoIwggTSMIIDuqADAgECAhN4AAAAA6hl
# waeH+YD/AAAAAAADMA0GCSqGSIb3DQEBCwUAMF8xCzAJBgNVBAYTAkNaMTcwNQYD
# VQQKEy5Wc2VvYmVjbmEgemRyYXZvdG5pIHBvamlzdG92bmEgQ2Vza2UgcmVwdWJs
# aWt5MRcwFQYDVQQDEw5WWlAtUG9saWN5LUNBMjAeFw0xNzA3MDIxNDEzMTVaFw0y
# NzA3MDIxNDIzMTVaMGExCzAJBgNVBAYTAkNaMTcwNQYDVQQKEy5Wc2VvYmVjbmEg
# emRyYXZvdG5pIHBvamlzdG92bmEgQ2Vza2UgcmVwdWJsaWt5MRkwFwYDVQQDExBW
# WlAtSW50cmFuZXQtQ0EyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
# t31VAwolUE0zQMHrH/UPeeUu4WDYXukM8croNjIpYMfUbpIyvYkw2sp39njKx0Cf
# cqpiOo4IoAYLcXZM0dv8RzTQi4ypsK+SCfTIWdqtg/jSFZMpifpLensI7smLoXHt
# Ek3+XwqQzDOLE3vBSY1YbotKy3fqMCbt/1XQRxOjJHL1/YZ6XieY46j2tHGmnXWM
# uTYBZ98Jv50jU244J4CA3+9/v6nFIk1lBLi9l0DrAljMKwlSoChC3YGtH5t9yUW+
# rUMLPUWbbnKK/yQZ0mk1cs8Unt8BopubLAzuuAUOC310K94GSKksK47JU0ZzDV7R
# Rl5oP3givA3uzn0213y3kwIDAQABo4IBgzCCAX8wEAYJKwYBBAGCNxUBBAMCAQAw
# HQYDVR0OBBYEFFNGECEkduJIS2IUyog3GBUq6SFqMBkGCSsGAQQBgjcUAgQMHgoA
# UwB1AGIAQwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQY
# MBaAFNuv4x6yXYbVDXK6sFnZY0/5+HWNMGwGA1UdHwRlMGMwYaBfoF2GLGh0dHA6
# Ly9jYS52enAuY3ovY2VydGRhdGEvVlpQLVBvbGljeS1DQTIuY3Jshi1odHRwOi8v
# cGtpLnZ6cC5jei9jZXJ0ZGF0YS9WWlAtUG9saWN5LUNBMi5jcmwwgYMGCCsGAQUF
# BwEBBHcwdTA4BggrBgEFBQcwAoYsaHR0cDovL2NhLnZ6cC5jei9jZXJ0ZGF0YS9W
# WlAtUG9saWN5LUNBMi5jcnQwOQYIKwYBBQUHMAKGLWh0dHA6Ly9wa2kudnpwLmN6
# L2NlcnRkYXRhL1ZaUC1Qb2xpY3ktQ0EyLmNydDANBgkqhkiG9w0BAQsFAAOCAQEA
# kMHMU5JUC0vRSpvU8md/OG+siYXKeLR8XT7X7Two7arDrscSlbFH+CP5TzbaS+Qw
# zrf5BCkpWbchcfyidJQYZ5Jq+iHhsTpzGvllU0ExnFURG8ZzAEJWqnLF5WW8xHUk
# 5KR3q7bWZx/eAWOic80IejJm8q5x76MbexNF3+ugizF2lK6HPECqrD3H65HYWxZo
# +2POtmX8UD3LFZYu9a5IycBHVYF2RqZ2n3iLazqC3O0noawkD7ceFRYVA+FGsSbP
# RmpADVhJfPnRqLMcKrT3ZzR/MlGMNshOxOFEARdTMcstBeC/qifQf5ltXzZAVnd1
# OJzHsMfrfVHVjtg4dclRtTCCBaUwggSNoAMCAQICE0oAAAACh/xKS0aIZFUAAAAA
# AAIwDQYJKoZIhvcNAQELBQAwXTELMAkGA1UEBhMCQ1oxNzA1BgNVBAoTLlZzZW9i
# ZWNuYSB6ZHJhdm90bmkgcG9qaXN0b3ZuYSBDZXNrZSByZXB1Ymxpa3kxFTATBgNV
# BAMTDFZaUC1Sb290LUNBMjAeFw0xNzA3MDIxMTQxNTVaFw0zNzA3MDIxMTUxNTVa
# MF8xCzAJBgNVBAYTAkNaMTcwNQYDVQQKEy5Wc2VvYmVjbmEgemRyYXZvdG5pIHBv
# amlzdG92bmEgQ2Vza2UgcmVwdWJsaWt5MRcwFQYDVQQDEw5WWlAtUG9saWN5LUNB
# MjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKloSBJ6JfgM00Sa2aFJ
# FIK9FJsuLtfTy+8BrE5ys8R/xpjaud6222jqpC38EIuvMhcKCAmyX0aNxZ+5VzOt
# z2aaYaHdsDAP1rFlNvr1E+4QRkm8bbpbNzBStsd6ebpBhcAK7ozCsxqF/T9vvWku
# PiRqJup5GPzBa8jfQtFAESNOr82TIznMzKmQA32z8iM/Nokov1EipukEjZYkHnRb
# 2ANEZ6LVqgB7At4S8wFCdNHmncj8Gie2WfOG6w9zOCt7elbWYp29aPIu4ep/DXL4
# Vb+2Ey9cSF/yq50SyPZlBcJmv8oXwH6UUc1pCuazmWwa4YTObwCryavPKq+nfT4z
# 1k8CAwEAAaOCAlowggJWMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBTbr+Me
# sl2G1Q1yurBZ2WNP+fh1jTCB3QYDVR0gBIHVMIHSMIHPBgsrgRqT0r9OAgEBADCB
# vzCBigYIKwYBBQUHAgIwfh58AEMAZQByAHQAaQBmAGkAawBhAGMAbgBpACAAcABy
# AG8AdgBhAGQAZQBjAGkAIABzAG0AZQByAG4AaQBjAGUAIABWAHMAZQBvAGIAZQBj
# AG4AZQAgAHoAZAByAGEAdgBvAHQAbgBpACAAcABvAGoAaQBzAHQAbwB2AG4AeTAw
# BggrBgEFBQcCARYkaHR0cDovL3BraS52enAuY3ovY2VydGRhdGEvQ1BTMi5odG1s
# MBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMB
# Af8EBTADAQH/MB8GA1UdIwQYMBaAFPIfGyPGvSCUwOJFNh/tTbn9VjV8MGgGA1Ud
# HwRhMF8wXaBboFmGKmh0dHA6Ly9jYS52enAuY3ovY2VydGRhdGEvVlpQLVJvb3Qt
# Q0EyLmNybIYraHR0cDovL3BraS52enAuY3ovY2VydGRhdGEvVlpQLVJvb3QtQ0Ey
# LmNybDB/BggrBgEFBQcBAQRzMHEwNgYIKwYBBQUHMAKGKmh0dHA6Ly9jYS52enAu
# Y3ovY2VydGRhdGEvVlpQLVJvb3QtQ0EyLmNydDA3BggrBgEFBQcwAoYraHR0cDov
# L3BraS52enAuY3ovY2VydGRhdGEvVlpQLVJvb3QtQ0EyLmNydDANBgkqhkiG9w0B
# AQsFAAOCAQEAOQNWSfXlPnAF3pk3P/gkqluxwsAeb9VnQ7xcHpm3pbxB73izWWMk
# XZymCseEVjknQCh0c8sutmCwJk1it5dQAch3Mu2/njMd7uun+Vh9Ai0kK0zlfIUA
# LLaL8j4h19dUxrtJyi2aMLvCAnFNK8rz48T/9Al/sS9/lGVJz+SyTgrFmEtbw5vB
# 2PcZiVjol2lgVe2+m0KOclCbvUhFqJEJPLrLjvOVHrUZEfY3tkS9UpA1Hw/ms6oT
# cpQHJjMMkcivJhzoDJTYz+5yq8x0UW0RuzUKHWF7P0xwhTwvM77g2bCFld4tgZEl
# CfHoEbMWe8+C6I/OGbjEfDiuqGLJRk+XojGCAhkwggIVAgEBMHgwYTELMAkGA1UE
# BhMCQ1oxNzA1BgNVBAoTLlZzZW9iZWNuYSB6ZHJhdm90bmkgcG9qaXN0b3ZuYSBD
# ZXNrZSByZXB1Ymxpa3kxGTAXBgNVBAMTEFZaUC1JbnRyYW5ldC1DQTICE0kAAcFZ
# IrhUcVtkziwAAAABwVkwCQYFKw4DAhoFAKB4MBgGCisGAQQBgjcCAQwxCjAIoAKA
# AKECgAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwIwYJKoZIhvcNAQkEMRYEFLT/2va2KeyFr6VZxwmzzSMb
# HeXLMA0GCSqGSIb3DQEBAQUABIIBAIB6NJ8UTbyn7D0ID0usQXvUk8qrjZbSVJXU
# sADmDDjGLJS8fx0TtaTt8MzQoop9ohLKO3iO/tfD1dtxz3cVfee43rbGQPggzCEI
# 5nO4qhnlL6Ic9ulJcn2XuFVoE6Bn7FUbOdg4S3T4q/FfOBkI+PPoAxUgJNDyQuhR
# 8PZqoj7rJpqpJu1Wl2USLlEaBJyAeR8Ply6rUbXS7Ob3WW4UcUi5U3Oo9LM6DU5/
# FyRxPc4Y7H4jIzVTKIVg610Ut9hcXy9OY7x+MsoxG55keU0VQdmuUu3eJiSUhJ9R
# 8WBPlmzbRHcYCmXdsaRdNrYU52QtDNTqpImFdgchGkurrNYZWis=
# SIG # End signature block
